controller_manager:
  ros__parameters:
    update_rate: 100  # Matching the Gazebo four_w_amr period of 0.001 s (1000 Hz)
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    publish_rate: 28.0  # Matching the update rate
    base_frame_id: base_link
    left_wheel_names: ['front_left_joint', 'back_left_joint']
    right_wheel_names: ['front_right_joint', 'back_right_joint']
    wheel_separation: 0.48
    wheel_radius: 0.065
    use_stamped_vel: false
    wheels_per_side: 2
